Fix bug with plantuml-filename in a directory
timofurrer/pandoc-plantuml-filter pull request #12
Opened 2019-11-26 17:27 UTC by Felixoid

With the latest version, it's impossible to use files within CWD for plantuml-filename.

I'm very open to another function name since not glad about the current one.

2019-11-29 07:38 UTC, Felixoid commented
Good morning @timofurrer. Do you have objections against this?

2019-12-30 13:03 UTC, Felixoid commented
Hey @timofurrer, I wish you a happy coming New Year.

Do you mind to merge it?

2020-02-04 18:50 UTC, timofurrer requested changes
I'll merge, once the `pass` statement is removed 🎉 

Thanks!

2020-02-04 18:50 UTC, timofurrer commented on pandoc_plantuml_filter.py
> +    pass
```suggestion
```

2020-02-04 19:17 UTC, Felixoid commented on pandoc_plantuml_filter.py
> +    pass
Thank you, cleaned out

2020-02-08 11:02 UTC, merged

2020-02-08 12:12 UTC, Felixoid commented
Thank you very much! Could you be so nice and release a new version to make me able to update the package in AUR? https://aur.archlinux.org/packages/pandoc-plantuml-filter-py/